@startuml

[root] --> [e] : ・
[root] --> [t] : ー

[e] --> [i] : ・
[e] --> [a] : ー
[t] --> [n] : ・
[t] --> [m] : ー

[i] --> [s] : ・
[i] --> [u] : ー
[a] --> [r] : ・
[a] --> [w] : ー
[n] --> [d] : ・
[n] --> [k] : ー
[m] --> [g] : ・
[m] --> [o] : ー

[s] --> [h] : ・
[s] --> [v] : ー
[u] --> [f] : ・
[u] --> [..--] : ー
[r] --> [l] : ・
[r] --> [.-.-] : ー
[w] --> [p] : ・
[w] --> [j] : ー
[d] --> [b] : ・
[d] --> [x] : ー
[k] --> [c] : ・
[k] --> [y] : ー
[g] --> [z] : ・
[g] --> [q] : ー
[o] --> [---.] : ・
[o] --> [---- ] : ー

[h] --> [5] : ・
[h] --> [4] : ー
'[v] --> [...-.] : ・
[v] --> [3] : ー
'[f] --> [..-..] : ・
'[f] --> [..-.-] : ー
[..--] --> [..--.] : ・
[..--] --> [2] : ー
'[l] --> [.-...] : ・
[l] --> [.-..-] : ー
[.-.-] --> [+] : ・
'[.-.-] --> [.-.--] : ー
'[p] --> [.--..] : ・
[p] --> [.--.-] : ー
'[j] --> [.---.] : ・
[j] --> [1] : ー
[b] --> [6] : ・
'[b] --> [-...-] : ー
[x] --> [/] : ・
'[x] --> [-..--] : ー
'[c] --> [-.-..] : ・
'[c] --> [-.-.-] : ー
[y] --> [(] : ・
'[y] --> [-.---] : ー
[z] --> [7] : ・
[z] --> [--..-] : ー
'[q] --> [--.-.] : ・
'[q] --> [--.--] : ー
[---.] --> [8] : ・
'[---.] --> [---.-] : ー
[---- ] --> [9] : ・
[---- ] --> [0] : ー

[5] --> [^] : ・
[^] --> [.......] : ・
[.......] --> [\b] : ・
[..--.] --> [?] : ・
[..--.] --> [_] : ー
[.-..-] --> ["] : ・
[+] --> [.] : ー
[.--.-] --> [@] : ・
[1] --> ['] : ・
[(] --> [)] : ー
[6] --> [-] : ー
[--..-] --> [,] : ー
[8] --> [:] : ・

 
@enduml